# Generated by Django 5.1.3 on 2024-12-12 11:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nom')),
                ('apercu_rapide', models.CharField(max_length=100, unique=True, verbose_name='Aperçue rapide')),
                ('description', models.CharField(max_length=5000, unique=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, unique=True, upload_to='./event_image', verbose_name='Image')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='./events_file', verbose_name="fichier de l'evenement")),
                ('like', models.PositiveIntegerField(default=0, null=True, verbose_name='liker')),
                ('dislike', models.PositiveIntegerField(default=0, null=True, verbose_name='disliker')),
            ],
            options={
                'verbose_name': 'Évenement',
                'verbose_name_plural': 'Évenements',
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, unique=True, verbose_name='Filière')),
                ('sigle', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Sigle')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
            },
        ),
        migrations.CreateModel(
            name='NiveauEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name="Niveau d'étude")),
            ],
            options={
                'verbose_name': "Niveau d'étude",
                'verbose_name_plural': "Niveaux d'études",
            },
        ),
        migrations.CreateModel(
            name='TypeOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True, unique=True, verbose_name='type')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nom')),
                ('university', models.CharField(blank=True, max_length=200, null=True, verbose_name='Université')),
                ('file', models.FileField(upload_to='./cours', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='fichier')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('publier', models.BooleanField(default=False, verbose_name='Publier le fichier')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('like', models.PositiveIntegerField(default=0, null=True, verbose_name='liker')),
                ('dislike', models.PositiveIntegerField(default=0, null=True, verbose_name='disliker')),
                ('downloads', models.PositiveIntegerField(default=0, null=True, verbose_name='Nombre de Télechargement')),
                ('publier_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiere_cours', to='UniWeb_13_024_7.filiere', verbose_name='Filière')),
                ('level', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level_cours', to='UniWeb_13_024_7.niveauetude', verbose_name='Niveau du cours')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='Etudiant', max_length=12, null=True, verbose_name='Status')),
                ('university', models.CharField(blank=True, default='Non définie', max_length=70, null=True, verbose_name='Universite')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./avatar_profil')),
                ('bio', models.CharField(blank=True, default='....Mon Biographie', max_length=255, null=True, verbose_name='Biographie')),
                ('filiere', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='UniWeb_13_024_7.filiere', verbose_name='Filière')),
                ('level', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='UniWeb_13_024_7.niveauetude', verbose_name="Niveau d'étude")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nom')),
                ('file', models.FileField(upload_to='./Document', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='fichier')),
                ('correction', models.FileField(blank=True, null=True, upload_to='./correction', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Correction')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='hash du fichier')),
                ('correction_hash', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='hash du correction')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('publier', models.BooleanField(default=False, verbose_name='Publier le fichier')),
                ('like', models.PositiveIntegerField(default=0, null=True, verbose_name='liker')),
                ('dislike', models.PositiveIntegerField(default=0, null=True, verbose_name='disliker')),
                ('downloads', models.PositiveIntegerField(default=0, null=True, verbose_name='Nombre de Télechargement')),
                ('publier_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('filiere', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filiere', to='UniWeb_13_024_7.filiere', verbose_name='Filière')),
                ('level', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='level', to='UniWeb_13_024_7.niveauetude', verbose_name='Niveau')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type', to='UniWeb_13_024_7.typeof')),
            ],
            options={
                'verbose_name': 'Exercie & Sujet',
                'verbose_name_plural': 'Exercices & Sujets',
            },
        ),
    ]
