# Generated by Django 5.1.3 on 2024-12-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filiere',
            name='sigle',
            field=models.CharField(default='', max_length=15, null=True, verbose_name='Sigle'),
        ),
        migrations.AlterField(
            model_name='niveauetude',
            name='name',
            field=models.CharField(default='', max_length=30, null=True, unique=True, verbose_name="Niveau d'étude"),
        ),
    ]
