# Generated by Django 5.1.3 on 2024-12-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0002_alter_filiere_sigle_alter_niveauetude_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='document',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='events',
            name='dislike',
        ),
        migrations.AlterField(
            model_name='cours',
            name='like',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='document',
            name='like',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='like'),
        ),
        migrations.AlterField(
            model_name='events',
            name='like',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='like'),
        ),
    ]
