# Generated by Django 5.1.3 on 2024-12-13 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0005_alter_documentlike_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentlike',
            old_name='pdf',
            new_name='document',
        ),
        migrations.AlterUniqueTogether(
            name='documentlike',
            unique_together={('user', 'document')},
        ),
        migrations.CreateModel(
            name='CoursLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True, verbose_name='like')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniWeb_13_024_7.cours', verbose_name='Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'unique_together': {('user', 'cours')},
            },
        ),
        migrations.CreateModel(
            name='EventLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True, verbose_name='like')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UniWeb_13_024_7.events', verbose_name='Document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'unique_together': {('user', 'event')},
            },
        ),
    ]
