# Generated by Django 5.1.3 on 2024-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0006_rename_pdf_documentlike_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Source'),
        ),
    ]
