# Generated by Django 5.1.3 on 2024-12-13 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0007_events_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courslike',
            options={'verbose_name': '#Like-Cours', 'verbose_name_plural': '#Like-Cours'},
        ),
        migrations.AlterModelOptions(
            name='documentlike',
            options={'verbose_name': '#Like-Document', 'verbose_name_plural': '#Like-Documents'},
        ),
        migrations.AlterModelOptions(
            name='eventlike',
            options={'verbose_name': '#Like-Évenements'},
        ),
        migrations.RemoveField(
            model_name='cours',
            name='like',
        ),
        migrations.RemoveField(
            model_name='document',
            name='like',
        ),
        migrations.RemoveField(
            model_name='events',
            name='like',
        ),
    ]
