# Generated by Django 5.1.3 on 2024-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0008_alter_courslike_options_alter_documentlike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='downloads',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Telechargement'),
        ),
    ]
