# Generated by Django 5.1.3 on 2024-12-13 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniWeb_13_024_7', '0009_events_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='./events_file', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name="fichier de l'evenement"),
        ),
    ]
